### ISSUE TITLE
Persistent identifier for this project?

### ISSUE THREAD

**Issue by wflynny** [BodenmillerGroup/napari-imc#24]
Hi @jwindhager, thank you for making this tool!  Substantially easier to use than past alternatives (e.g. histocat).  

I'd like to cite this tool in a manuscript; any thoughts about a persistent DOI for this plugin ([Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) or something else)?

Cheers

**Comment by jwindhager** [comment]
Hi @wflynny, thanks so much for your kind feedback and for giving credit! For now, you can cite the following preprint, as part of which napari-imc was published: https://www.biorxiv.org/content/10.1101/2021.11.12.468357v1. Let me know if this is sufficient, or whether you require a versioned & archived way of citing napari-imc (e.g. using Zenodo, as you suggested). Cheers

**Comment by wflynny** [comment]
Perfect, that'll work just fine!  Cheers.
