### ISSUE TITLE
No plugin found

### ISSUE THREAD

**Issue by kvetab** [BodenmillerGroup/napari-imc#27]
Hi, 
I have been trying to install napari-imc unsuccessfully on mac using conda. I get "No plugin found capable of reading ..." when I tried to open a .mdc file. I noticed the issues about napari-imc not working with newer napari and readimc versions, so I downgraded those, but it only changed the error output a little, the error remains the same. Traceback is as follows:

```
(napariimc) cemmXWMD7TRWJP:~ kbrazdilova$ napari ~/Projects/CMM_013/CMM_013_10708.mcd
/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py:383: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _MACOS_AT_LEAST_CATALINA = sys.platform == "darwin" and StrictVersion(
/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py:385: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) > StrictVersion('19.0.0')
/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py:386: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _MACOS_AT_LEAST_BIG_SUR = sys.platform == "darwin" and StrictVersion(
/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py:388: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) > StrictVersion('20.0.0')
09:35:21 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Could not find a backend to open `/Users/kbrazdilova/Projects/CMM_013/CMM_013_10708.mcd`` with iomode `ri`.')
    in file: /Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/imageio/core/imopen.py
    at line: 303
     author: napari team
      email: napari-steering-council@googlegroups.com
    package: napari
        url: https://napari.org
    version: 0.4.9

Traceback (most recent call last):
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py", line 418, in <module>
    sys.exit(main())
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py", line 414, in main
    _run()
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/__main__.py", line 298, in _run
    viewer = view_path(  # noqa: F841
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/view_layers.py", line 169, in view_path
    return _make_viewer_then('open', args, kwargs)
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/view_layers.py", line 119, in _make_viewer_then
    method(*args, **kwargs)
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/components/viewer_model.py", line 857, in open
    self._add_layers_with_plugins(
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/components/viewer_model.py", line 902, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/Users/kbrazdilova/opt/miniconda3/envs/napariimc/lib/python3.9/site-packages/napari/plugins/io.py", line 131, in read_data_with_plugins
    raise ValueError(message)
ValueError: No plugin found capable of reading '/Users/kbrazdilova/Projects/CMM_013/CMM_013_10708.mcd'.
```

When I open napari first and then open the file in the GUI, it also fails with the same error. I tried installing the napari-imc plugin in the GUI, which showed "installing" for a few seconds and then stopped and the plugin was not added to list of installed plugins. 

I also tried erasing the environment, installing through pip, through conda, in different order, anything I could think of.

It seems the plugin is there, but it's not talking to napari. Can anyone please point me in the right direction how to solve this issue? Thanks!

**Comment by jwindhager** [comment]
Hi @kvetab, thanks for the thorough report and trying all the different methods!

napari-imc should work with the latest stable releases of napari (0.4.16) and readimc (0.6.1), so no need to downgrade. 

Opening mcd files should work both via the command-line and via File --> Open File(s), there shouldn't be any difference.

Could you maybe post the output of `conda list -n napariimc` here?

I just created a fresh environment using conda/pip as follows, and opening an mcd file seems to work for me:
```bash
conda create -n napari-imc python=3.10
conda activate napari-imc
pip install "napari[all]" napari-imc
napari /path/to/my/file.mcd
```

I just noticed that when installing napari from conda-forge, an outdated version of Qt seems to be installed, see to #28. Also, there seem to be issues related to napari installed via conda and Qt (pyside2 backend) on Mac, see https://github.com/napari/napari/issues/5231. While not causally related to this issue, I for now recommend installing napari using pip as shown above. Hope this helps.

**Comment by kvetab** [comment]
Hi @jwindhager,
Thank you for the very swift reply. I recreated the environment yet again and installed using the commands you provided - and magically it works! How typical, as soon as I ask for help it starts working :) 
Not sure what the problem was, but thanks anyway.
