### ISSUE TITLE
Add colour legend to viewer

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imc#3]
Hey, it would be super nice if you can add a colour legend to the viewer - otherwise it's a bit hard to see which markers are being displayed.

**Comment by jwindhager** [comment]
Thanks for the suggestion. Unfortunately, napari doesn't support such "visible layer legends" out of the box. Feel free to open an issue with the napari project, though, they are quite active. One could potentially implement this as a plugin to napari, but for now I consider this out of the scope of the napari-imc package, sorry. If desperately needed we can have a discussion offline, @nilseling.
