### ISSUE TITLE
ROIs and panaorama don't seem to match

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imc#4]
Hey, I checked a couple of .mcds and in none of them the ROIs overlay with the panorama - I will give you the .mcds for testing. This was tested on macOS 10.15.17 using the `napari-imc` conda environment running `napari-imc` v0.1.0.

**Comment by jwindhager** [comment]
Thank you for reporting this, @nilseling! I will look into it. Is this concerning user-uploaded panorama images (i.e., image files that the user manually adds to the mcd) or ROI panoramas generated by the machine?

**Comment by nilseling** [comment]
I was talking about the machine generated panorama ROIs. Sorry for not being specific

**Comment by jwindhager** [comment]
This is due to https://github.com/BodenmillerGroup/imctools/issues/104

**Comment by jwindhager** [comment]
Closed accidentally, reopening

**Comment by jwindhager** [comment]
Closed with imctools v2.1.1
